url: https://sinemete.github.io
baseurl: /pengout/

# Site settings
title: PengOut
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Damla Eda Bıçakcı
  pic: 1
  position: Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Babanazar Gutlygeldiyev
  pic: 2
  position: Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sine Mete
  pic: 3
  position: Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Pegah Soltani
  pic: 4
  position: Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: #
      
- name: Hasan Selim Yağçı
  pic: 5
  position: Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://
  - title: facebook
    url:
  - title: github
    url: http://github.com/github.com/babazar/pengout
  - title: stack-overflow
    url: http://
  - title: bitbucket 
    url: http://
  

# Postal address (add as many lines as necessary)
address:
  - line: Bilkent University
  - line: Ankara

# Build settings
markdown: kramdown
permalink: pretty
